baseURL = 'https://example.org/'
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Pedro Bentes'
favicon = 'favicon.ico'

[menus]
  # Main menu
  [[menus.main]]
    name = 'Blog'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    url = '/'
    weight = 11

  # Footer menu
  [[menus.footer]]
    name = 'Github'
    url = '/'
    weight = 10
  [[menus.footer]]
    name = 'Twitter'
    url = 'https://www.x.com/pbentesio'
    weight = 11
  [[menus.footer]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/pgbentes/'
    weight = 12
  [[menus.footer]]
    name = 'RSS'
    url = 'index.xml'
    weight = 13